### ISSUE TITLE
API and library feedback

### ISSUE THREAD

**Issue by vurtun** [nguillemot/JustGL#1]
Like I promised I will provide some feedback to your library. **Disclaimer: all points I am goint to make are mostly nitpicks and are not meant to personally attack you or the library. It is meant as an overview of what somebody will see if he will encounter your library and I am not here to discuss since it already takes enough time to write this (exception of course if something is not understandable or clear enough. You decide what you take away from this not I.**
1. First impression
   I have no idea what this project is supposed to do from your Readme. What does this project do on which platforms in which extend with what limitations,... . This: `JustGL Just GL it!` is waste of my time and screams at me not to use your library. It is not cute and only signals that the one who wrote this library is a beginner and has no idea what he is doing even before actually reading source code. If I would encounter your library I would directly close the Tab after reading this. For a quick example I have absolutely no idea what language and version you are using is it C89,C99,C11 C++98, C++11..
2. "How to use"
   These three points are just aweful. First of the first line is giving me no information what so ever. Basically if I just drop the header in my project file nothing will work. Why? because I also have to include it and build it. In addition I need information if any special libraries, headers or dependencies are required to actually build it.  This again would be a barrier for me and I would not use this library, since to much information is missing.
   Second point suddenly you tell the user to fill out a template that dictates how he should write his code if using your code. This is not about your library this is about the users code and his problem that he wants to be solved. Most of the time especially for better programmers they could solve the problem themself (maybe even better than you!) but if you can save them time and don't force them to think and write code like you or even worse in this case structure code like the library dictates, them they will use a library. (This all stems from the word `template` which means a fixed code structure which has to be filled like an excel sheet).
   This was only the first two lines and the third gets even worse. Suddenly you tell me to do things like copy things out of your file and paste it into a new file (and I am purposely ignoring the optionally). Why should I do this and why did you not do this. I probably know but someone who will encounter your library will not. These kind of lines without more context just confuse the possible user and will make them close the Tab.
   This also ties in with the question what is a single header library and why would you do something like that and how does it work. All questions that need to me answered.

Ok from here on I will stop about the readme and go into the code.
1. "(Sorry about that, but we can’t show files that are this big right now.)"
   This would cause me to directly close the tab. A file that is so big that I can't look at it with syntax highlighting in github is a problem. I know that you had to copy a lot of OpenGL definition into this header but the possible user will not and will not take the time to find it out. By the way I purposely don't try to write any possible solutions and only state the problem and the consequence and you have to come up with solutions or trade offs.
2. Namespace
   Since this is a C library (at least from what I can tell) you need a namespace for types and especially functions (most of the time 2-3 letters or short word followed with underscore). If I have a project I never ever would use a library that has a potential risk of cluttering my global namespace and cause naming problems or clashes especially with name beginning with GetXXX. I will not get deeper into this issue because there is already so much written on the internet about it and I don't want or hopefully need to explain this.
3. **Never include header files in header files (maybe except stddef.h if required)**
   Another issue which should be avoided at all cost. If you have a header and _absolutely_ cannot live without another header file (which should never happen in 99.99% of all cases) than it is ok to include it in the header file. I know your views may differ but again there is so much written about it on the internet and I will not go into details or start a discussion. I will just say if you just add headers like the big "windows.h" it is a reason for me and many others to close the tab and forget the library (personally I would go even further and would disregard a library that includes a standard header in its header). I checked again and it seems the 'windows.h' is for the glext.h portion but this does not change my view on the topic (you decide on the trade off).
4. API + Implementation
   OK this is a mess. Before going any further I have to ask you if you want me to continue and if so provide me with more information of what _exactly_ you want to achieve with this library. The whole library got really hairy from here on and violates almost everything I know about API design and we would get into territory which would require me to write a lot.

**Comment by nlguillemot** [comment]
I replied in tweets, so here's a screenshot of the thread https://twitter.com/nlguillemot/status/708274816801857537
![tweets](https://cloud.githubusercontent.com/assets/1079061/13702939/f588161a-e746-11e5-8244-cbd83591afc2.PNG)

**Comment by vurtun** [comment]
First of you don't have explain anything to me (except for the actual question I asked what this library does). I am just documenting so there is no need to defend anything to me if you decide that something needs to be the way it is then it will be I will **not** fight for anything. I only write what I was thinking while opening and reading your project for the first time and **you** decide what to make out of it. So I don't care for the reason why things are the way they are these are only observations and you don't have to explain things to me. Instead what I tried to convey is that you have to tell the one visiting your library why things are like the are.

As for the 'windows.h' header you are right it is hard to read code without syntax highlighting, there are still the standard library headers but I already expressed my view on that.

About the code size issue and I know why it is as big as it is. The question is if and what you will do about it (**you** decide the tradeoffs not me) since it is something that **might** turn users off. You can leave it as it is I don't care but you should know that it can be a problem.

The dependencies again I know because I know how single header libraries work I wrote 6 of them. Other programmers might not, the question is do you want to explain it or leave it and disregard possible users (again only **your** choice I don't care).

Namespace again you don't have to defend this against me I don't care but if had to decide as a possible user this is something which is a deal breaker for me (small tip: don't judge users), I state what I see and what could cause problems for users and you decide if you care or not.

The reason why I write this in a rather negative tone is because I want to show that people who visit your project don't care about you and will not use your library for the smallest reason. One thing I learned is that for libraries you have to remove yourself as much as possible from the code and provide something that is acceptable for as many people as possible. So anything that can be a problem _will_ be a problem for someone.

**Comment by nlguillemot** [comment]
I want to prepare a document that explains the philosophy of project. I appreciate talking about it with you, since it helps me put it into words.

The big idea is that I'm trying to remove everything I consider "software engineering" from my code, to do projects where my mind is focused 100% on computer graphics. I noticed I was more creative and more productive as a programmer when I knew nothing about software engineering, so I want to bring that feeling back. For these reasons, the project is deliberately under-engineered.

I've done 4 projects with this library so far, ranging from 1 day to 1 week. It has been enjoyable, so I consider it a success so far. I'll have to publish some example programs when I have some free time.

**Comment by vurtun** [comment]
> The big idea is that I'm trying to remove everything I consider "software engineering" from my code, to do projects where my mind is focused 100% on computer graphics. I noticed I was more creative and more productive as a programmer when I knew nothing about software engineering, so I want to bring that feeling back. For these reasons, the project is deliberately under-engineered.

OK this is quite important to make clear since it changes the expectations for this library immensely. For example the library uses a framework design which takes away control the most of all libraries design code structures but works if the actual use case is small or rather narrow enough. 

> I've done 4 projects with this library so far, ranging from 1 day to 1 week. It has been enjoyable, so I consider it a success so far. I'll have to publish some example programs when I have some free time.

While it changes the expectation you have to be aware that this approach has a high possibility or danger of being something that only works for you or only a small subset of people. I would especially highlight how this library is good for these use cases you just described with a range from 1 day to 1 week.

I would also think about how to extend the library for these use cases since you take away a lot of control from the user and you need to make sure that you provide enough so that user profit in the end by using your library. For example you could provide things like hot reloading of code or data (shaders or other file content) which actually would make this library special and something along side shadertoy and worth using for prototyping which requires a lot of features and does not require a lot of control.
